#ifndef NRF52832_GPIOTE_MAP_H
#define NRF52832_GPIOTE_MAP_H

#define GPIOTE_BASE                 0x40006000L

#define GPIOTE_TASKS_OUT_ADDR(_n)   (GPIOTE_BASE + ((_n) << 2))
#define GPIOTE_TASKS_SET_ADDR(_n)   (GPIOTE_BASE + 0x030 + ((_n) << 2))
#define GPIOTE_TASKS_CLR_ADDR(_n)   (GPIOTE_BASE + 0x060 + ((_n) << 2))
#define GPIOTE_EVENTS_IN_ADDR(_n)   (GPIOTE_BASE + 0x100 + ((_n) << 2))
#define GPIOTE_EVENTS_PORT_ADDR     (GPIOTE_BASE + 0x17C)

#define GPIOTE_INTENSET_ADDR        (GPIOTE_BASE + 0x304)
#define GPIOTE_INTENSET_IN_MSK(_n)  (1u << (_n))
#define GPIOTE_INTENSET_PORT_MSK    (1u << 31)

#define GPIOTE_INTENCLR_ADDR        (GPIOTE_BASE + 0x308)
#define GPIOTE_INTENCLR_IN_MSK(_n)  (1u << (_n))
#define GPIOTE_INTENCLR_PORT_MSK    (1u << 31)

#define GPIOTE_CONFIG_ADDR(_n)      (GPIOTE_BASE + 0x510 + ((_n) << 2))
#define GPIOTE_CONFIG_MODE_POS      0
#define GPIOTE_CONFIG_MODE_MSK      (3u << GPIOTE_CONFIG_MODE_POS)
#define GPIOTE_CONFIG_MODE_DISABLED (0u << GPIOTE_CONFIG_MODE_POS)
#define GPIOTE_CONFIG_MODE_EVENT    (1u << GPIOTE_CONFIG_MODE_POS)
#define GPIOTE_CONFIG_MODE_TASK     (3u << GPIOTE_CONFIG_MODE_POS)

#define GPIOTE_CONFIG_PSEL_POS      8
#define GPIOTE_CONFIG_PSEL_MSK      (31u << GPIOTE_CONFIG_PSEL_POS)
#define GPIOTE_CONFIG_PSEL(_pin)    (((uint32_t)(_pin) << GPIOTE_CONFIG_PSEL_POS) & GPIOTE_CONFIG_PSEL_MSK)

#define GPIOTE_CONFIG_POLARITY_POS      16
#define GPIOTE_CONFIG_POLARITY_MSK      (3u << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_NONE     (0u << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_LOTOHI   (1u << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_HITOLO   (2u << GPIOTE_CONFIG_POLARITY_POS)
#define GPIOTE_CONFIG_POLARITY_TOGGLE   (3u << GPIOTE_CONFIG_POLARITY_POS)

#define GPIOTE_CONFIG_OUTINIT_POS   20
#define GPIOTE_CONFIG_OUTINIT_MSK   (1u << GPIOTE_CONFIG_OUTINIT_POS)
#define GPIOTE_CONFIG_OUTINIT_LOW   (0u << GPIOTE_CONFIG_OUTINIT_POS)
#define GPIOTE_CONFIG_OUTINIT_HIGH  (1u << GPIOTE_CONFIG_OUTINIT_POS)

#endif
